version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    container_name: universal_scrobbler_redis
    restart: unless-stopped
    command: >
      redis-server
        --requirepass scrobble-dev-pass
        --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
