# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: automix_talk_rules.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'automix_talk_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.provided_track_pb2 as provided__track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61utomix_talk_rules.proto\x12\"spotify.player.proto.state_restore\x1a\x14provided_track.proto\"x\n\x10\x41utomixTalkRules\x12H\n\rcurrent_track\x18\x01 \x01(\x0b\x32\x31.spotify.player.proto.state_restore.ProvidedTrack\x12\x1a\n\x12narration_duration\x18\x02 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'automix_talk_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTOMIXTALKRULES']._serialized_start=86
  _globals['_AUTOMIXTALKRULES']._serialized_end=206
# @@protoc_insertion_point(module_scope)
