# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: circuit_breaker_rules.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'circuit_breaker_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ircuit_breaker_rules.proto\x12\"spotify.player.proto.state_restore\"m\n\x13\x43ircuitBreakerRules\x12\x1c\n\x14\x64iscarded_track_uids\x18\x01 \x03(\t\x12\x1a\n\x12num_errored_tracks\x18\x02 \x02(\x05\x12\x1c\n\x14\x63ontext_track_played\x18\x03 \x02(\x08\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'circuit_breaker_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_CIRCUITBREAKERRULES']._serialized_start=67
  _globals['_CIRCUITBREAKERRULES']._serialized_end=176
# @@protoc_insertion_point(module_scope)
