# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: context_player_options.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'context_player_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ontext_player_options.proto\x12\x14spotify.player.proto\"\xf1\x01\n\x14\x43ontextPlayerOptions\x12\x19\n\x11shuffling_context\x18\x01 \x01(\x08\x12\x19\n\x11repeating_context\x18\x02 \x01(\x08\x12\x17\n\x0frepeating_track\x18\x03 \x01(\x08\x12\x16\n\x0eplayback_speed\x18\x04 \x01(\x02\x12\x44\n\x05modes\x18\x05 \x03(\x0b\x32\x35.spotify.player.proto.ContextPlayerOptions.ModesEntry\x1a,\n\nModesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x81\x02\n\x1c\x43ontextPlayerOptionOverrides\x12\x19\n\x11shuffling_context\x18\x01 \x01(\x08\x12\x19\n\x11repeating_context\x18\x02 \x01(\x08\x12\x17\n\x0frepeating_track\x18\x03 \x01(\x08\x12\x16\n\x0eplayback_speed\x18\x04 \x01(\x02\x12L\n\x05modes\x18\x05 \x03(\x0b\x32=.spotify.player.proto.ContextPlayerOptionOverrides.ModesEntry\x1a,\n\nModesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_player_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_CONTEXTPLAYEROPTIONS_MODESENTRY']._loaded_options = None
  _globals['_CONTEXTPLAYEROPTIONS_MODESENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXTPLAYEROPTIONOVERRIDES_MODESENTRY']._loaded_options = None
  _globals['_CONTEXTPLAYEROPTIONOVERRIDES_MODESENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXTPLAYEROPTIONS']._serialized_start=55
  _globals['_CONTEXTPLAYEROPTIONS']._serialized_end=296
  _globals['_CONTEXTPLAYEROPTIONS_MODESENTRY']._serialized_start=252
  _globals['_CONTEXTPLAYEROPTIONS_MODESENTRY']._serialized_end=296
  _globals['_CONTEXTPLAYEROPTIONOVERRIDES']._serialized_start=299
  _globals['_CONTEXTPLAYEROPTIONOVERRIDES']._serialized_end=556
  _globals['_CONTEXTPLAYEROPTIONOVERRIDES_MODESENTRY']._serialized_start=252
  _globals['_CONTEXTPLAYEROPTIONOVERRIDES_MODESENTRY']._serialized_end=296
# @@protoc_insertion_point(module_scope)
