# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kitteh_box_rules.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'kitteh_box_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16kitteh_box_rules.proto\x12\"spotify.player.proto.state_restore\"\x83\x04\n\x0eKittehBoxRules\x12Y\n\x0cnode_aspects\x18\x01 \x03(\x0b\x32\x43.spotify.player.proto.state_restore.KittehBoxRules.NodeAspectsEntry\x12H\n\x03pos\x18\x02 \x02(\x0e\x32;.spotify.player.proto.state_restore.KittehBoxRules.Position\x12V\n\x0flast_transition\x18\x03 \x02(\x0e\x32=.spotify.player.proto.state_restore.KittehBoxRules.Transition\x12\x19\n\x11\x63ontext_iteration\x18\x04 \x02(\x05\x12\x17\n\x0fpending_skip_to\x18\x05 \x02(\x08\x12\x12\n\npage_index\x18\x06 \x01(\x03\x1a.\n\x10NodeAspectsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"7\n\nTransition\x12\x0b\n\x07\x41\x44VANCE\x10\x00\x12\r\n\tSKIP_NEXT\x10\x01\x12\r\n\tSKIP_PREV\x10\x02\"C\n\x08Position\x12\x12\n\x0e\x42\x45TWEEN_TRACKS\x10\x00\x12\x10\n\x0cON_DELIMITER\x10\x01\x12\x11\n\rON_NODE_TRACK\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kitteh_box_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KITTEHBOXRULES']._serialized_start=63
  _globals['_KITTEHBOXRULES']._serialized_end=578
  _globals['_KITTEHBOXRULES_NODEASPECTSENTRY']._serialized_start=406
  _globals['_KITTEHBOXRULES_NODEASPECTSENTRY']._serialized_end=452
  _globals['_KITTEHBOXRULES_TRANSITION']._serialized_start=454
  _globals['_KITTEHBOXRULES_TRANSITION']._serialized_end=509
  _globals['_KITTEHBOXRULES_POSITION']._serialized_start=511
  _globals['_KITTEHBOXRULES_POSITION']._serialized_end=578
# @@protoc_insertion_point(module_scope)
