# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging_params.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'logging_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14logging_params.proto\x12\x14spotify.player.proto\"\xb1\x01\n\rLoggingParams\x12\x1e\n\x16\x63ommand_initiated_time\x18\x01 \x01(\x03\x12\x1d\n\x15\x63ommand_received_time\x18\x02 \x01(\x03\x12\x19\n\x11page_instance_ids\x18\x03 \x03(\t\x12\x17\n\x0finteraction_ids\x18\x04 \x03(\t\x12\x19\n\x11\x64\x65vice_identifier\x18\x05 \x01(\t\x12\x12\n\ncommand_id\x18\x06 \x01(\tB\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_LOGGINGPARAMS']._serialized_start=47
  _globals['_LOGGINGPARAMS']._serialized_end=224
# @@protoc_insertion_point(module_scope)
