# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x14spotify.common.media*`\n\x0c\x41udioQuality\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06NORMAL\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\r\n\tVERY_HIGH\x10\x04\x12\x08\n\x04HIFI\x10\x05\x12\x0b\n\x07HIFI_24\x10\x06\x42\x1c\n\x18\x63om.spotify.common.protoH\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.spotify.common.protoH\002'
  _globals['_AUDIOQUALITY']._serialized_start=37
  _globals['_AUDIOQUALITY']._serialized_end=133
# @@protoc_insertion_point(module_scope)
