# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mft_rules_inject_filler_tracks.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mft_rules_inject_filler_tracks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.context_track_pb2 as context__track__pb2
import scripts.protos.random_source_pb2 as random__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$mft_rules_inject_filler_tracks.proto\x12\"spotify.player.proto.state_restore\x1a\x13\x63ontext_track.proto\x1a\x13random_source.proto\"r\n\x17MftRandomTrackInjection\x12G\n\rrandom_source\x18\x01 \x02(\x0b\x32\x30.spotify.player.proto.state_restore.RandomSource\x12\x0e\n\x06offset\x18\x02 \x02(\x05\"\xba\x02\n\x1aMftRulesInjectFillerTracks\x12;\n\x0f\x66\x61llback_tracks\x18\x01 \x03(\x0b\x32\".spotify.player.proto.ContextTrack\x12\\\n\x17padding_track_injection\x18\x02 \x02(\x0b\x32;.spotify.player.proto.state_restore.MftRandomTrackInjection\x12G\n\rrandom_source\x18\x03 \x02(\x0b\x32\x30.spotify.player.proto.state_restore.RandomSource\x12\x1f\n\x17\x66ilter_explicit_content\x18\x04 \x02(\x08\x12\x17\n\x0f\x66\x65\x61ture_classes\x18\x05 \x03(\tB\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mft_rules_inject_filler_tracks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_MFTRANDOMTRACKINJECTION']._serialized_start=118
  _globals['_MFTRANDOMTRACKINJECTION']._serialized_end=232
  _globals['_MFTRULESINJECTFILLERTRACKS']._serialized_start=235
  _globals['_MFTRULESINJECTFILLERTRACKS']._serialized_end=549
# @@protoc_insertion_point(module_scope)
