# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mft_rules_core.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mft_rules_core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.mft_context_switch_rules_pb2 as mft__context__switch__rules__pb2
import scripts.protos.mft_rules_inject_filler_tracks_pb2 as mft__rules__inject__filler__tracks__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14mft_rules_core.proto\x12\"spotify.player.proto.state_restore\x1a\x1emft_context_switch_rules.proto\x1a$mft_rules_inject_filler_tracks.proto\"\xde\x01\n\x0cMftRulesCore\x12\\\n\x14inject_filler_tracks\x18\x01 \x02(\x0b\x32>.spotify.player.proto.state_restore.MftRulesInjectFillerTracks\x12W\n\x14\x63ontext_switch_rules\x18\x02 \x02(\x0b\x32\x39.spotify.player.proto.state_restore.MftContextSwitchRules\x12\x17\n\x0f\x66\x65\x61ture_classes\x18\x03 \x03(\tB\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mft_rules_core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_MFTRULESCORE']._serialized_start=131
  _globals['_MFTRULESCORE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
