# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mod_rules_interruptions.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mod_rules_interruptions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.player_license_pb2 as player__license__pb2
import scripts.protos.provided_track_pb2 as provided__track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmod_rules_interruptions.proto\x12\"spotify.player.proto.state_restore\x1a\x14player_license.proto\x1a\x14provided_track.proto\"\xc8\x03\n\x15ModRulesInterruptions\x12L\n\x11seek_repeat_track\x18\x01 \x01(\x0b\x32\x31.spotify.player.proto.state_restore.ProvidedTrack\x12\x11\n\tprng_seed\x18\x02 \x02(\r\x12\x15\n\rsupport_video\x18\x03 \x02(\x08\x12\x18\n\x10is_active_action\x18\x04 \x02(\x08\x12\x19\n\x11is_in_seek_repeat\x18\x05 \x02(\x08\x12\x1f\n\x17has_tp_api_restrictions\x18\x06 \x02(\x08\x12i\n\x13interruption_source\x18\x07 \x02(\x0e\x32L.spotify.player.proto.state_restore.ModRulesInterruptions.InterruptionSource\x12\x34\n\x07license\x18\x08 \x02(\x0b\x32#.spotify.player.proto.PlayerLicense\"@\n\x12InterruptionSource\x12\x0b\n\x07\x43ONTEXT\x10\x01\x12\x07\n\x03SAS\x10\x02\x12\x14\n\x10NO_INTERRUPTIONS\x10\x03\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mod_rules_interruptions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_MODRULESINTERRUPTIONS']._serialized_start=114
  _globals['_MODRULESINTERRUPTIONS']._serialized_end=570
  _globals['_MODRULESINTERRUPTIONS_INTERRUPTIONSOURCE']._serialized_start=506
  _globals['_MODRULESINTERRUPTIONS_INTERRUPTIONSOURCE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
