# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: player_session.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'player_session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.context_track_pb2 as context__track__pb2
import scripts.protos.context_player_options_pb2 as context__player__options__pb2
import scripts.protos.logging_params_pb2 as logging__params__pb2
import scripts.protos.play_origin_pb2 as play__origin__pb2
import scripts.protos.player_license_pb2 as player__license__pb2
import scripts.protos.prepare_play_options_pb2 as prepare__play__options__pb2
import scripts.protos.context_loader_pb2 as context__loader__pb2
import scripts.protos.context_player_rules_pb2 as context__player__rules__pb2
import scripts.protos.playback_state_pb2 as playback__state__pb2
import scripts.protos.player_session_fake_pb2 as player__session__fake__pb2
import scripts.protos.provided_track_pb2 as provided__track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14player_session.proto\x12\"spotify.player.proto.state_restore\x1a\x13\x63ontext_track.proto\x1a\x1c\x63ontext_player_options.proto\x1a\x14logging_params.proto\x1a\x11play_origin.proto\x1a\x14player_license.proto\x1a\x1aprepare_play_options.proto\x1a\x14\x63ontext_loader.proto\x1a\x1a\x63ontext_player_rules.proto\x1a\x14playback_state.proto\x1a\x19player_session_fake.proto\x1a\x14provided_track.proto\"\xe7\x07\n\rPlayerSession\x12\x46\n\x14prepare_play_options\x18\x01 \x02(\x0b\x32(.spotify.player.proto.PreparePlayOptions\x12I\n\x0eplayback_state\x18\x02 \x01(\x0b\x32\x31.spotify.player.proto.state_restore.PlaybackState\x12@\n\x05track\x18\x03 \x01(\x0b\x32\x31.spotify.player.proto.state_restore.ProvidedTrack\x12<\n\x10track_to_skip_to\x18\x04 \x01(\x0b\x32\".spotify.player.proto.ContextTrack\x12\x19\n\x11given_playback_id\x18\x05 \x01(\x0c\x12H\n\x1bnext_command_logging_params\x18\x06 \x02(\x0b\x32#.spotify.player.proto.LoggingParams\x12H\n\x1b\x63urr_command_logging_params\x18\x07 \x02(\x0b\x32#.spotify.player.proto.LoggingParams\x12\x35\n\x0bplay_origin\x18\x08 \x02(\x0b\x32 .spotify.player.proto.PlayOrigin\x12\x12\n\nis_playing\x18\t \x02(\x08\x12\x11\n\tis_paused\x18\n \x02(\x08\x12\x1b\n\x13is_system_initiated\x18\x0b \x02(\x08\x12\x13\n\x0bis_finished\x18\x0c \x02(\x08\x12;\n\x07options\x18\r \x02(\x0b\x32*.spotify.player.proto.ContextPlayerOptions\x12\x15\n\rplayback_seed\x18\x0e \x02(\x04\x12\x14\n\x0cnum_advances\x18\x0f \x02(\x05\x12\x15\n\rdid_skip_prev\x18\x10 \x02(\x08\x12\x34\n\x07license\x18\x11 \x02(\x0b\x32#.spotify.player.proto.PlayerLicense\x12\x45\n\x05rules\x18\x12 \x02(\x0b\x32\x36.spotify.player.proto.state_restore.ContextPlayerRules\x12\x41\n\x06loader\x18\x13 \x02(\x0b\x32\x31.spotify.player.proto.state_restore.ContextLoader\x12\x43\n\x04\x66\x61ke\x18\x64 \x01(\x0b\x32\x35.spotify.player.proto.state_restore.PlayerSessionFake')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERSESSION']._serialized_start=324
  _globals['_PLAYERSESSION']._serialized_end=1323
# @@protoc_insertion_point(module_scope)
