# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: player_session_fake.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'player_session_fake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.context_pb2 as context__pb2
import scripts.protos.context_player_state_pb2 as context__player__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19player_session_fake.proto\x12\"spotify.player.proto.state_restore\x1a\rcontext.proto\x1a\x1a\x63ontext_player_state.proto\"\xad\x01\n\x11PlayerSessionFake\x12L\n\x0cplayer_state\x18\x01 \x02(\x0b\x32\x36.spotify.player.proto.state_restore.ContextPlayerState\x12\x35\n\x0eplayer_context\x18\x02 \x02(\x0b\x32\x1d.spotify.player.proto.Context\x12\x13\n\x0bis_finished\x18\x03 \x02(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_session_fake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERSESSIONFAKE']._serialized_start=109
  _globals['_PLAYERSESSIONFAKE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
