# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playback_quality.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'playback_quality.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16playback_quality.proto\x12\"spotify.player.proto.state_restore\"\xd8\x02\n\x0fPlaybackQuality\x12G\n\rbitrate_level\x18\x01 \x01(\x0e\x32\x30.spotify.player.proto.state_restore.BitrateLevel\x12\x45\n\x08strategy\x18\x02 \x01(\x0e\x32\x33.spotify.player.proto.state_restore.BitrateStrategy\x12N\n\x14target_bitrate_level\x18\x03 \x01(\x0e\x32\x30.spotify.player.proto.state_restore.BitrateLevel\x12 \n\x18target_bitrate_available\x18\x04 \x01(\x08\x12\x43\n\x0bhifi_status\x18\x05 \x01(\x0e\x32..spotify.player.proto.state_restore.HiFiStatus*m\n\x0c\x42itrateLevel\x12\x19\n\x15unknown_bitrate_level\x10\x00\x12\x07\n\x03low\x10\x01\x12\n\n\x06normal\x10\x02\x12\x08\n\x04high\x10\x03\x12\r\n\tvery_high\x10\x04\x12\x08\n\x04hifi\x10\x05\x12\n\n\x06hifi24\x10\x06*\x83\x01\n\x0f\x42itrateStrategy\x12\x14\n\x10unknown_strategy\x10\x00\x12\x11\n\rbest_matching\x10\x01\x12\x13\n\x0f\x62\x61\x63kend_advised\x10\x02\x12\x11\n\rofflined_file\x10\x03\x12\x0f\n\x0b\x63\x61\x63hed_file\x10\x04\x12\x0e\n\nlocal_file\x10\x05*\'\n\nHiFiStatus\x12\x08\n\x04none\x10\x00\x12\x07\n\x03off\x10\x01\x12\x06\n\x02on\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playback_quality_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BITRATELEVEL']._serialized_start=409
  _globals['_BITRATELEVEL']._serialized_end=518
  _globals['_BITRATESTRATEGY']._serialized_start=521
  _globals['_BITRATESTRATEGY']._serialized_end=652
  _globals['_HIFISTATUS']._serialized_start=654
  _globals['_HIFISTATUS']._serialized_end=693
  _globals['_PLAYBACKQUALITY']._serialized_start=63
  _globals['_PLAYBACKQUALITY']._serialized_end=407
# @@protoc_insertion_point(module_scope)
