# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playback_state.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'playback_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.playback_quality_pb2 as playback__quality__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14playback_state.proto\x12\"spotify.player.proto.state_restore\x1a\x16playback_quality.proto\"\xd3\x01\n\rPlaybackState\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12 \n\x18position_as_of_timestamp\x18\x02 \x01(\x05\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x12\x14\n\x0cis_buffering\x18\x04 \x01(\x08\x12M\n\x10playback_quality\x18\x05 \x01(\x0b\x32\x33.spotify.player.proto.state_restore.PlaybackQuality\x12\x16\n\x0eplayback_speed\x18\x06 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playback_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYBACKSTATE']._serialized_start=85
  _globals['_PLAYBACKSTATE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
