# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prepare_play_options.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'prepare_play_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.context_player_options_pb2 as context__player__options__pb2
import scripts.protos.player_license_pb2 as player__license__pb2
import scripts.protos.skip_to_track_pb2 as skip__to__track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprepare_play_options.proto\x12\x14spotify.player.proto\x1a\x1c\x63ontext_player_options.proto\x1a\x14player_license.proto\x1a\x13skip_to_track.proto\"\x95\x05\n\x12PreparePlayOptions\x12S\n\x17player_options_override\x18\x01 \x01(\x0b\x32\x32.spotify.player.proto.ContextPlayerOptionOverrides\x12\x34\n\x07license\x18\x02 \x01(\x0b\x32#.spotify.player.proto.PlayerLicense\x12\x63\n\x16\x63onfiguration_override\x18\x03 \x03(\x0b\x32\x43.spotify.player.proto.PreparePlayOptions.ConfigurationOverrideEntry\x12\x13\n\x0bplayback_id\x18\x04 \x01(\t\x12\x1d\n\x15\x61lways_play_something\x18\x05 \x01(\x08\x12\x38\n\rskip_to_track\x18\x06 \x01(\x0b\x32!.spotify.player.proto.SkipToTrack\x12\x0f\n\x07seek_to\x18\x07 \x01(\x03\x12\x18\n\x10initially_paused\x18\x08 \x01(\x08\x12\x18\n\x10system_initiated\x18\t \x01(\x08\x12\x14\n\x0csuppressions\x18\n \x03(\t\x12;\n\x0eprefetch_level\x18\x0b \x01(\x0e\x32#.spotify.player.proto.PrefetchLevel\x12\x12\n\nsession_id\x18\x0c \x01(\t\x12\x37\n\x0c\x61udio_stream\x18\r \x01(\x0e\x32!.spotify.player.proto.AudioStream\x1a<\n\x1a\x43onfigurationOverrideEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*$\n\rPrefetchLevel\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05MEDIA\x10\x01*%\n\x0b\x41udioStream\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05\x41LARM\x10\x01\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prepare_play_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_PREPAREPLAYOPTIONS_CONFIGURATIONOVERRIDEENTRY']._loaded_options = None
  _globals['_PREPAREPLAYOPTIONS_CONFIGURATIONOVERRIDEENTRY']._serialized_options = b'8\001'
  _globals['_PREFETCHLEVEL']._serialized_start=789
  _globals['_PREFETCHLEVEL']._serialized_end=825
  _globals['_AUDIOSTREAM']._serialized_start=827
  _globals['_AUDIOSTREAM']._serialized_end=864
  _globals['_PREPAREPLAYOPTIONS']._serialized_start=126
  _globals['_PREPAREPLAYOPTIONS']._serialized_end=787
  _globals['_PREPAREPLAYOPTIONS_CONFIGURATIONOVERRIDEENTRY']._serialized_start=727
  _globals['_PREPAREPLAYOPTIONS_CONFIGURATIONOVERRIDEENTRY']._serialized_end=787
# @@protoc_insertion_point(module_scope)
