# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: provided_track.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'provided_track.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.protos.restrictions_pb2 as restrictions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14provided_track.proto\x12\"spotify.player.proto.state_restore\x1a\x12restrictions.proto\"\xb8\x03\n\rProvidedTrack\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12Q\n\x08metadata\x18\x03 \x03(\x0b\x32?.spotify.player.proto.state_restore.ProvidedTrack.MetadataEntry\x12\x10\n\x08provider\x18\x04 \x01(\t\x12\x0f\n\x07removed\x18\x05 \x03(\t\x12\x0f\n\x07\x62locked\x18\x06 \x03(\t\x12\x62\n\x11internal_metadata\x18\x07 \x03(\x0b\x32G.spotify.player.proto.state_restore.ProvidedTrack.InternalMetadataEntry\x12\x38\n\x0crestrictions\x18\x08 \x01(\x0b\x32\".spotify.player.proto.Restrictions\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x37\n\x15InternalMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'provided_track_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_PROVIDEDTRACK_METADATAENTRY']._loaded_options = None
  _globals['_PROVIDEDTRACK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PROVIDEDTRACK_INTERNALMETADATAENTRY']._loaded_options = None
  _globals['_PROVIDEDTRACK_INTERNALMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_PROVIDEDTRACK']._serialized_start=81
  _globals['_PROVIDEDTRACK']._serialized_end=521
  _globals['_PROVIDEDTRACK_METADATAENTRY']._serialized_start=417
  _globals['_PROVIDEDTRACK_METADATAENTRY']._serialized_end=464
  _globals['_PROVIDEDTRACK_INTERNALMETADATAENTRY']._serialized_start=466
  _globals['_PROVIDEDTRACK_INTERNALMETADATAENTRY']._serialized_end=521
# @@protoc_insertion_point(module_scope)
