# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remove_banned_tracks_rules.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'remove_banned_tracks_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n remove_banned_tracks_rules.proto\x12\"spotify.player.proto.state_restore\"\x1a\n\x07Strings\x12\x0f\n\x07strings\x18\x01 \x03(\t\"\xbd\x02\n\x17RemoveBannedTracksRules\x12\x15\n\rbanned_tracks\x18\x01 \x03(\t\x12\x15\n\rbanned_albums\x18\x02 \x03(\t\x12\x16\n\x0e\x62\x61nned_artists\x18\x03 \x03(\t\x12s\n\x15\x62\x61nned_context_tracks\x18\x04 \x03(\x0b\x32T.spotify.player.proto.state_restore.RemoveBannedTracksRules.BannedContextTracksEntry\x1ag\n\x18\x42\x61nnedContextTracksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12:\n\x05value\x18\x02 \x01(\x0b\x32+.spotify.player.proto.state_restore.Strings:\x02\x38\x01\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remove_banned_tracks_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_REMOVEBANNEDTRACKSRULES_BANNEDCONTEXTTRACKSENTRY']._loaded_options = None
  _globals['_REMOVEBANNEDTRACKSRULES_BANNEDCONTEXTTRACKSENTRY']._serialized_options = b'8\001'
  _globals['_STRINGS']._serialized_start=72
  _globals['_STRINGS']._serialized_end=98
  _globals['_REMOVEBANNEDTRACKSRULES']._serialized_start=101
  _globals['_REMOVEBANNEDTRACKSRULES']._serialized_end=418
  _globals['_REMOVEBANNEDTRACKSRULES_BANNEDCONTEXTTRACKSENTRY']._serialized_start=315
  _globals['_REMOVEBANNEDTRACKSRULES_BANNEDCONTEXTTRACKSENTRY']._serialized_end=418
# @@protoc_insertion_point(module_scope)
