# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resume_points_rules.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'resume_points_rules.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19resume_points_rules.proto\x12\"spotify.player.proto.state_restore\"K\n\x0bResumePoint\x12\x17\n\x0fis_fully_played\x18\x01 \x02(\x08\x12\x10\n\x08position\x18\x02 \x02(\x03\x12\x11\n\ttimestamp\x18\x03 \x02(\x03\"\xd9\x01\n\x11ResumePointsRules\x12^\n\rresume_points\x18\x01 \x03(\x0b\x32G.spotify.player.proto.state_restore.ResumePointsRules.ResumePointsEntry\x1a\x64\n\x11ResumePointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12>\n\x05value\x18\x02 \x01(\x0b\x32/.spotify.player.proto.state_restore.ResumePoint:\x02\x38\x01\x42\x02H\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resume_points_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\002'
  _globals['_RESUMEPOINTSRULES_RESUMEPOINTSENTRY']._loaded_options = None
  _globals['_RESUMEPOINTSRULES_RESUMEPOINTSENTRY']._serialized_options = b'8\001'
  _globals['_RESUMEPOINT']._serialized_start=65
  _globals['_RESUMEPOINT']._serialized_end=140
  _globals['_RESUMEPOINTSRULES']._serialized_start=143
  _globals['_RESUMEPOINTSRULES']._serialized_end=360
  _globals['_RESUMEPOINTSRULES_RESUMEPOINTSENTRY']._serialized_start=260
  _globals['_RESUMEPOINTSRULES_RESUMEPOINTSENTRY']._serialized_end=360
# @@protoc_insertion_point(module_scope)
