"""add playback_session table

Revision ID: 0b1eebecf821
Revises: 434e35d70b0b
Create Date: 2025-09-07 22:35:56.565155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b1eebecf821'
down_revision: Union[str, None] = '434e35d70b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_session',
    sa.Column('session_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('play_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_ms', sa.Integer(), nullable=False),
    sa.Column('active_device', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['appuser.user_uuid'], ),
    sa.PrimaryKeyConstraint('session_uuid'),
    sa.UniqueConstraint('user_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playback_session')
    # ### end Alembic commands ###
