"""adding formats

Revision ID: 13e81762529d
Revises: cd4bdd68cf0f
Create Date: 2025-09-02 09:11:58.126823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13e81762529d'
down_revision: Union[str, None] = 'cd4bdd68cf0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_album_format',
    sa.Column('collection_uuid', sa.Uuid(), nullable=False),
    sa.Column('album_uuid', sa.Uuid(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_uuid', 'album_uuid'], ['collection_album_bridge.collection_uuid', 'collection_album_bridge.album_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_uuid', 'album_uuid', 'format')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_album_format')
    # ### end Alembic commands ###
