"""added collection models

Revision ID: 1b75f781daa8
Revises: fa372e2e829b
Create Date: 2025-04-02 19:26:23.207619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b75f781daa8'
down_revision: Union[str, None] = 'fa372e2e829b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('device', 'device_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('playback_history', 'played_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_column('playback_history', 'spotify_track_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('spotify_track_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('playback_history', 'played_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device', 'device_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('device', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
