"""added styles

Revision ID: 1dab07a29b09
Revises: 893526e42826
Create Date: 2025-04-29 09:50:46.067647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dab07a29b09'
down_revision: Union[str, None] = '893526e42826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style',
    sa.Column('style_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_parent_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['style_parent_uuid'], ['style.style_uuid'], ),
    sa.PrimaryKeyConstraint('style_uuid')
    )
    op.create_table('style_style_mapping',
    sa.Column('from_style_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_style_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_style_uuid'], ['style.style_uuid'], ),
    sa.ForeignKeyConstraint(['to_style_uuid'], ['style.style_uuid'], ),
    sa.PrimaryKeyConstraint('from_style_uuid', 'to_style_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_style_mapping')
    op.drop_table('style')
    # ### end Alembic commands ###
