"""added collection models

Revision ID: 2c968b2a61c1
Revises: 4c1622272f84
Create Date: 2025-03-30 01:06:00.456951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c968b2a61c1'
down_revision: Union[str, None] = '4c1622272f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_release', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('album_release', sa.Column('image_thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_release', 'image_thumbnail_url')
    op.drop_column('album_release', 'image_url')
    # ### end Alembic commands ###
