"""add playback queue table

Revision ID: 434e35d70b0b
Revises: 59cb67d75fd4
Create Date: 2025-09-07 14:55:35.192635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '434e35d70b0b'
down_revision: Union[str, None] = '59cb67d75fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_queue',
    sa.Column('playback_queue_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('track_version_uuid', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['track_version_uuid'], ['track_version.track_version_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['appuser.user_uuid'], ),
    sa.PrimaryKeyConstraint('playback_queue_uuid'),
    sa.UniqueConstraint('user_uuid', 'position', name='uq_playbackqueue_user_position')
    )
    with op.batch_alter_table('playback_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playback_queue_user_uuid'), ['user_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playback_queue_user_uuid'))

    op.drop_table('playback_queue')
    # ### end Alembic commands ###
