"""added playbackhistory session_id for grouping

Revision ID: 46220d005e37
Revises: 7034daee8514
Create Date: 2025-09-15 21:19:48.064555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46220d005e37'
down_revision: Union[str, None] = '7034daee8514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_uuid', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'playback_session', ['session_uuid'], ['session_uuid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_uuid')

    # ### end Alembic commands ###
