"""Add file_scan_cache table

Revision ID: 59cb67d75fd4
Revises: 7810a8c2f054
Create Date: 2025-09-03 13:53:02.766064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '59cb67d75fd4'
down_revision: Union[str, None] = '7810a8c2f054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_scan_cache',
    sa.Column('file_scan_uuid', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('file_scan_uuid')
    )
    with op.batch_alter_table('file_scan_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_scan_cache_path'), ['path'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_scan_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_scan_cache_path'))

    op.drop_table('file_scan_cache')
    # ### end Alembic commands ###
