"""add images to album

Revision ID: 5c105e2ee1ef
Revises: 78d6b7236a91
Create Date: 2025-04-06 23:41:05.811520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c105e2ee1ef'
down_revision: Union[str, None] = '78d6b7236a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('album', sa.Column('image_thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'image_thumbnail_url')
    op.drop_column('album', 'image_url')
    # ### end Alembic commands ###
