"""added collection models

Revision ID: 5c9b6eec8205
Revises: fafa2cdeb6b2
Create Date: 2025-03-28 20:13:12.931768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c9b6eec8205'
down_revision: Union[str, None] = 'fafa2cdeb6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discogs_token',
    sa.Column('discogs_token_uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['appuser.user_uuid'], ),
    sa.PrimaryKeyConstraint('discogs_token_uuid'),
    sa.UniqueConstraint('discogs_token_uuid'),
    sa.UniqueConstraint('user_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discogs_token')
    # ### end Alembic commands ###
