"""adding reduced style vectors

Revision ID: 655f986b20e5
Revises: e9bbd2333160
Create Date: 2025-05-10 19:03:17.946590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '655f986b20e5'
down_revision: Union[str, None] = 'e9bbd2333160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_vector', sa.Column('style_vector_reduced', Vector(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_vector', 'style_vector_reduced')
    # ### end Alembic commands ###
