"""added playbacksession timestamps

Revision ID: 7034daee8514
Revises: 8795c3c6a1d6
Create Date: 2025-09-15 21:03:05.568015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7034daee8514'
down_revision: Union[str, None] = '8795c3c6a1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM playback_history;")
    op.execute("DELETE FROM playback_session;")
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.drop_column('ended_at')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
