"""adding collectionTrack

Revision ID: 7810a8c2f054
Revises: 13e81762529d
Create Date: 2025-09-02 10:24:23.740791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7810a8c2f054'
down_revision: Union[str, None] = '13e81762529d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_track',
    sa.Column('collection_track_uuid', sa.Uuid(), nullable=False),
    sa.Column('collection_uuid', sa.Uuid(), nullable=False),
    sa.Column('track_version_uuid', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_uuid'], ['collection.collection_uuid'], ),
    sa.ForeignKeyConstraint(['track_version_uuid'], ['track_version.track_version_uuid'], ),
    sa.PrimaryKeyConstraint('collection_track_uuid'),
    sa.UniqueConstraint('collection_uuid', 'track_version_uuid', 'format')
    )
    op.create_index(op.f('ix_collection_track_collection_uuid'), 'collection_track', ['collection_uuid'], unique=False)
    op.create_index(op.f('ix_collection_track_track_version_uuid'), 'collection_track', ['track_version_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_track_track_version_uuid'), table_name='collection_track')
    op.drop_index(op.f('ix_collection_track_collection_uuid'), table_name='collection_track')
    op.drop_table('collection_track')
    # ### end Alembic commands ###
