"""added album type field

Revision ID: 7c974afc9105
Revises: ab53cfa7c512
Create Date: 2025-04-24 11:12:22.182727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c974afc9105'
down_revision: Union[str, None] = 'ab53cfa7c512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_type',
    sa.Column('album_type_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('album_type_uuid')
    )
    op.create_table('albumtypebridge',
    sa.Column('album_uuid', sa.Uuid(), nullable=False),
    sa.Column('album_type_uuid', sa.Uuid(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['album_type_uuid'], ['album_type.album_type_uuid'], ),
    sa.ForeignKeyConstraint(['album_uuid'], ['album.album_uuid'], ),
    sa.PrimaryKeyConstraint('album_uuid', 'album_type_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albumtypebridge')
    op.drop_table('album_type')
    # ### end Alembic commands ###
