"""add duration to collectionTrack

Revision ID: 7f85ca55c653
Revises: 0b1eebecf821
Create Date: 2025-09-07 22:45:55.604063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f85ca55c653'
down_revision: Union[str, None] = '0b1eebecf821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_track', schema=None) as batch_op:
        batch_op.drop_column('duration_ms')

    # ### end Alembic commands ###
