"""remove played/skipped from PlaybackQueue

Revision ID: 839f31d58ad4
Revises: bb0c365e8bc0
Create Date: 2025-09-08 22:23:50.940387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '839f31d58ad4'
down_revision: Union[str, None] = 'bb0c365e8bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_queue', schema=None) as batch_op:
        batch_op.drop_column('skipped')
        batch_op.drop_column('played')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('played', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('skipped', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
