"""simplified playbackhistory

Revision ID: 8d396b31d9f6
Revises: a1b2c3d4e5f6
Create Date: 2025-09-09 19:38:31.362815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d396b31d9f6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('spotify_track_id')
        batch_op.drop_column('full_play')
        batch_op.drop_column('is_still_playing')

    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'current_registered',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.drop_column('current_registered')

    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_still_playing', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('full_play', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('spotify_track_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
