"""added collection models

Revision ID: 8fd2f7dd01bd
Revises: a76313ca8031
Create Date: 2025-03-28 23:59:52.829067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fd2f7dd01bd'
down_revision: Union[str, None] = 'a76313ca8031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discogs_token', sa.Column('access_token_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('discogs_token', 'token_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discogs_token', sa.Column('token_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('discogs_token', 'access_token_secret')
    # ### end Alembic commands ###
