"""added collection models

Revision ID: 910c229d234d
Revises: fc39db5e5c8f
Create Date: 2025-03-28 23:33:27.668674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '910c229d234d'
down_revision: Union[str, None] = 'fc39db5e5c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discogs_token', 'token_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discogs_token', sa.Column('token_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
