"""added collection models

Revision ID: 96b8f38780c7
Revises: 1b75f781daa8
Create Date: 2025-04-02 19:56:42.129999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96b8f38780c7'
down_revision: Union[str, None] = '1b75f781daa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('album_uuid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'playback_history', 'album', ['album_uuid'], ['album_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playback_history', type_='foreignkey')
    op.drop_column('playback_history', 'album_uuid')
    # ### end Alembic commands ###
