"""updated stuff


Revision ID: 990e11fa021b
Revises: b3712d756f61
Create Date: 2025-03-25 03:00:18.489611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '990e11fa021b'
down_revision: Union[str, None] = 'b3712d756f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('is_still_playing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playback_history', 'is_still_playing')
    # ### end Alembic commands ###
