"""added tagstylematch table

Revision ID: 9d992c510f3a
Revises: 1dab07a29b09
Create Date: 2025-04-29 20:58:25.372717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d992c510f3a'
down_revision: Union[str, None] = '1dab07a29b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_style_match',
    sa.Column('tag_uuid', sa.Uuid(), nullable=False),
    sa.Column('style_uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('tag_uuid', 'style_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_style_match')
    # ### end Alembic commands ###
