"""added playback columns for progress and current state

Revision ID: a0972fe73b58
Revises: fb55560f726e
Create Date: 2025-03-24 23:34:45.011421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0972fe73b58'
down_revision: Union[str, None] = 'fb55560f726e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('playback_history', sa.Column('progress_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playback_history', 'progress_ms')
    op.drop_column('playback_history', 'duration_ms')
    # ### end Alembic commands ###
