"""added collection models

Revision ID: a76313ca8031
Revises: 910c229d234d
Create Date: 2025-03-28 23:49:10.176596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a76313ca8031'
down_revision: Union[str, None] = '910c229d234d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discogs_token', sa.Column('token_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discogs_token', 'token_secret')
    # ### end Alembic commands ###
