"""adding device and source field

Revision ID: ab8379bed441
Revises: 8d396b31d9f6
Create Date: 2025-09-09 19:46:05.175597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab8379bed441'
down_revision: Union[str, None] = '8d396b31d9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), server_default='Streaming', nullable=False))

    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_device_uuid', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key("fk_playback_session_device", 'device', ['active_device_uuid'], ['device_uuid'])
        batch_op.drop_column('active_device')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_device', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint("fk_playback_session_device", type_="foreignkey")
        batch_op.drop_column('active_device_uuid')

    with op.batch_alter_table('playback_history', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
