"""added scrobble

Revision ID: af12fed609cb
Revises: 63e2f1b8c3e7
Create Date: 2025-03-22 19:59:36.915877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af12fed609cb'
down_revision: Union[str, None] = '63e2f1b8c3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_history',
    sa.Column('playback_history_uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('spotify_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('track_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discogs_release_id', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['appuser.user_uuid'], ),
    sa.PrimaryKeyConstraint('playback_history_uuid'),
    sa.UniqueConstraint('playback_history_uuid')
    )
    op.create_unique_constraint(None, 'spotifytoken', ['spotify_token_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotifytoken', type_='unique')
    op.drop_table('playback_history')
    # ### end Alembic commands ###
