"""empty message

Revision ID: b3712d756f61
Revises: a0972fe73b58
Create Date: 2025-03-24 23:41:24.430474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3712d756f61'
down_revision: Union[str, None] = 'a0972fe73b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('full_play', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playback_history', 'full_play')
    # ### end Alembic commands ###
