"""add current_queue_uuid to PlaybackSession

Revision ID: bb0c365e8bc0
Revises: 6b640c9f4d47
Create Date: 2025-09-08 22:19:38.741848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb0c365e8bc0'
down_revision: Union[str, None] = '6b640c9f4d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_track', schema=None) as batch_op:
        batch_op.alter_column('added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('file_scan_cache', schema=None) as batch_op:
        batch_op.alter_column('scanned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('playback_queue', schema=None) as batch_op:
        batch_op.alter_column('added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)

    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_queue_uuid', sa.Uuid(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'playback_queue', ['current_queue_uuid'], ['playback_queue_uuid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_column('current_queue_uuid')

    with op.batch_alter_table('playback_queue', schema=None) as batch_op:
        batch_op.alter_column('added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('file_scan_cache', schema=None) as batch_op:
        batch_op.alter_column('scanned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('collection_track', schema=None) as batch_op:
        batch_op.alter_column('added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)

    # ### end Alembic commands ###
