"""added artist tag table

Revision ID: c612a7032a74
Revises: ed35eaf34ffc
Create Date: 2025-04-08 22:35:41.175745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c612a7032a74'
down_revision: Union[str, None] = 'ed35eaf34ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_tag_bridge',
    sa.Column('artist_uuid', sa.Uuid(), nullable=False),
    sa.Column('tag_uuid', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_uuid'], ['artist.artist_uuid'], ),
    sa.ForeignKeyConstraint(['tag_uuid'], ['tag.tag_uuid'], ),
    sa.PrimaryKeyConstraint('artist_uuid', 'tag_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_tag_bridge')
    # ### end Alembic commands ###
