"""added musicbrainz_id_field

Revision ID: d6a49168648d
Revises: c612a7032a74
Create Date: 2025-04-08 22:38:05.604296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6a49168648d'
down_revision: Union[str, None] = 'c612a7032a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('musicbrainz_artist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_artist_musicbrainz_artist_id'), 'artist', ['musicbrainz_artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_musicbrainz_artist_id'), table_name='artist')
    op.drop_column('artist', 'musicbrainz_artist_id')
    # ### end Alembic commands ###
