"""added collection models

Revision ID: deaee7746415
Revises: 96b8f38780c7
Create Date: 2025-04-02 23:53:51.584800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'deaee7746415'
down_revision: Union[str, None] = '96b8f38780c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('spotify_track_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playback_history', 'spotify_track_id')
    # ### end Alembic commands ###
