"""adding vectors

Revision ID: e9bbd2333160
Revises: 4746f569192b
Create Date: 2025-05-10 11:24:54.034901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'e9bbd2333160'
down_revision: Union[str, None] = '4746f569192b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_vector',
    sa.Column('album_uuid', sa.Uuid(), nullable=False),
    sa.Column('artist_vector', Vector(dim=512), nullable=False),
    sa.Column('year_vector', Vector(dim=1), nullable=False),
    sa.Column('type_vector', Vector(dim=17), nullable=False),
    sa.Column('style_vector', Vector(dim=5478), nullable=False),
    sa.PrimaryKeyConstraint('album_uuid')
    )
    op.create_index(op.f('ix_album_vector_album_uuid'), 'album_vector', ['album_uuid'], unique=False)
    op.drop_table('album_graph_embedding')
    op.drop_table('album_umap_embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_umap_embedding',
    sa.Column('album_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('album_uuid', name='album_umap_embedding_pkey')
    )
    op.create_table('album_graph_embedding',
    sa.Column('album_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', Vector(dim=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('album_uuid', name='album_graph_embedding_pkey')
    )
    op.drop_index(op.f('ix_album_vector_album_uuid'), table_name='album_vector')
    op.drop_table('album_vector')
    # ### end Alembic commands ###
