"""added duraation to track

Revision ID: ed35eaf34ffc
Revises: 5c105e2ee1ef
Create Date: 2025-04-07 11:21:09.733049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed35eaf34ffc'
down_revision: Union[str, None] = '5c105e2ee1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'duration')
    # ### end Alembic commands ###
