"""removed_old_vector_column

Revision ID: f166b077285e
Revises: 655f986b20e5
Create Date: 2025-05-11 09:40:59.806614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f166b077285e'
down_revision: Union[str, None] = '655f986b20e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album_vector', 'style_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_vector', sa.Column('style_vector', pgvector.sqlalchemy.vector.VECTOR(dim=5478), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
