"""remove constraints

Revision ID: f44f6e177002
Revises: 735206db19a6
Create Date: 2025-09-15 21:35:41.653204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f44f6e177002'
down_revision: Union[str, None] = '735206db19a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.drop_constraint('playback_session_user_uuid_key', type_='unique')
        batch_op.create_index('ix_playback_session_user_uuid', ['user_uuid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_session', schema=None) as batch_op:
        batch_op.create_unique_constraint('playback_session_user_uuid_key', ['user_uuid'])
        batch_op.drop_index('ix_playback_session_user_uuid')
    # ### end Alembic commands ###
