"""added collection models

Revision ID: fa372e2e829b
Revises: ef1cb81b141d
Create Date: 2025-04-02 18:26:52.246632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa372e2e829b'
down_revision: Union[str, None] = 'ef1cb81b141d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('device_uuid', sa.Uuid(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['appuser.user_uuid'], ),
    sa.PrimaryKeyConstraint('device_uuid')
    )
    op.add_column('playback_history', sa.Column('device_uuid', sa.Uuid(), nullable=False))
    op.drop_constraint('playback_history_album_release_uuid_fkey', 'playback_history', type_='foreignkey')
    op.drop_constraint('playback_history_album_uuid_fkey', 'playback_history', type_='foreignkey')
    op.drop_constraint('playback_history_artist_uuid_fkey', 'playback_history', type_='foreignkey')
    op.create_foreign_key(None, 'playback_history', 'device', ['device_uuid'], ['device_uuid'])
    op.drop_column('playback_history', 'album_uuid')
    op.drop_column('playback_history', 'artist_uuid')
    op.drop_column('playback_history', 'album_release_uuid')
    op.drop_column('playback_history', 'device_name')
    op.drop_column('playback_history', 'progress_ms')
    op.drop_column('playback_history', 'duration_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_history', sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('playback_history', sa.Column('progress_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('playback_history', sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('playback_history', sa.Column('album_release_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('playback_history', sa.Column('artist_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('playback_history', sa.Column('album_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'playback_history', type_='foreignkey')
    op.create_foreign_key('playback_history_artist_uuid_fkey', 'playback_history', 'artist', ['artist_uuid'], ['artist_uuid'])
    op.create_foreign_key('playback_history_album_uuid_fkey', 'playback_history', 'album', ['album_uuid'], ['album_uuid'])
    op.create_foreign_key('playback_history_album_release_uuid_fkey', 'playback_history', 'album_release', ['album_release_uuid'], ['album_release_uuid'])
    op.drop_column('playback_history', 'device_uuid')
    op.drop_table('device')
    # ### end Alembic commands ###
