"""empty message

Revision ID: fb55560f726e
Revises: af12fed609cb
Create Date: 2025-03-22 20:13:18.734493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb55560f726e'
down_revision: Union[str, None] = 'af12fed609cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'playback_history', ['playback_history_uuid'])
    op.add_column('spotifytoken', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotifytoken', 'scope')
    op.drop_constraint(None, 'playback_history', type_='unique')
    # ### end Alembic commands ###
