name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change this if you want to specify a different OS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH for secure connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Run deployment script over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          export PATH="$HOME/.local/bin:$PATH"
          cd ~/UniversalScrobbler
          git pull
          sudo -S systemctl stop uvicorn.service
          cd api
          poetry install --no-root
          poetry run alembic upgrade head
          cd ../ui
          npm install
          npm run build
          sudo -S systemctl start uvicorn.service